import { StyleSheet } from 'react-native';

export const callScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#111',
        alignItems: 'center',
        justifyContent: 'center',
    },
    text: {
        color: 'white',
        marginTop: 10,
    },
    connectionActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginTop: 24,
    },
    retryButton: {
        backgroundColor: '#7C3AED',
        paddingHorizontal: 18,
        paddingVertical: 12,
        borderRadius: 12,
    },
    exitButton: {
        backgroundColor: '#374151',
    },
    retryButtonText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '700',
    },
    connectingOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: '#111',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 20,
    },
    videoGrid: {
        flex: 1,
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    participant: {
        position: 'relative',
        overflow: 'hidden',
    },
    video: {
        width: '100%',
        height: '100%',
    },
    participantLabel: {
        position: 'absolute',
        bottom: 8,
        left: 8,
        backgroundColor: 'rgba(0,0,0,0.6)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    participantName: {
        color: '#fff',
        fontSize: 12,
    },
    interpreterLayout: {
        flex: 1,
        flexDirection: 'row',
    },
    mainVideoArea: {
        flex: 1,
    },
    mainParticipant: {
        flex: 1,
        position: 'relative',
    },
    interpreterMainLabel: {
        position: 'absolute',
        left: 16,
        right: 16,
        backgroundColor: 'rgba(124, 58, 237, 0.9)',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 12,
        alignItems: 'center',
    },
    interpreterMainName: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '700',
    },
    participantsSidebar: {
        width: 120,
        backgroundColor: '#0a0a0a',
        borderLeftWidth: 2,
        borderLeftColor: '#333',
    },
    sidebarVideo: {
        height: 160,
        position: 'relative',
        borderBottomWidth: 1,
        borderBottomColor: '#333',
    },
    sidebarLabel: {
        position: 'absolute',
        bottom: 4,
        left: 4,
        right: 4,
        backgroundColor: 'rgba(0,0,0,0.7)',
        paddingHorizontal: 4,
        paddingVertical: 2,
        borderRadius: 4,
        alignItems: 'center',
    },
    sidebarName: {
        color: '#fff',
        fontSize: 9,
        fontWeight: '500',
    },
    interpreterSidebar: {
        width: 130,
        backgroundColor: '#1a1a1a',
        borderLeftWidth: 2,
        borderLeftColor: '#7C3AED',
    },
    interpreterVideo: {
        flex: 1,
        position: 'relative',
    },
    interpreterLabel: {
        position: 'absolute',
        bottom: 4,
        left: 4,
        right: 4,
        backgroundColor: 'rgba(124, 58, 237, 0.8)',
        paddingHorizontal: 6,
        paddingVertical: 3,
        borderRadius: 4,
        alignItems: 'center',
    },
    interpreterName: {
        color: '#fff',
        fontSize: 10,
        fontWeight: '600',
    },
    layoutToggleButton: {
        position: 'absolute',
        top: 50,
        right: 16,
        backgroundColor: 'rgba(0,0,0,0.7)',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 20,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        zIndex: 10,
    },
    layoutToggleText: {
        fontSize: 16,
    },
    layoutToggleLabel: {
        color: '#fff',
        fontSize: 12,
        fontWeight: '500',
    },
    controlsContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'rgba(15, 15, 20, 0.85)',
        paddingTop: 16,
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        alignItems: 'center',
        paddingHorizontal: 20,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        zIndex: 50,
    },
    button: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: '#fff',
        justifyContent: 'center',
        alignItems: 'center',
    },
    buttonDisabled: {
        backgroundColor: '#ef4444',
    },
    hangupButton: {
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: '#dc2626',
    },
    pipRestoreButton: {
        position: 'absolute',
        top: 20,
        left: 20,
        backgroundColor: 'rgba(0,0,0,0.5)',
        width: 50,
        height: 50,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 100,
    },
    minimizeButton: {
        position: 'absolute',
        top: 50,
        left: 16,
        backgroundColor: 'rgba(0,0,0,0.7)',
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10,
    },
    controlsContainerMini: {
        bottom: 10,
        transform: [{ scale: 0.8 }],
    },
    participantTranscriptionContainer: {
        position: 'absolute',
        left: 8,
        right: 8,
        alignItems: 'center',
        zIndex: 100,
    },
    transcriptionCloseButton: {
        alignSelf: 'flex-end',
        marginBottom: 3,
        marginRight: 2,
        width: 18,
        height: 18,
        borderRadius: 9,
        backgroundColor: 'rgba(0, 0, 0, 0.55)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    transcriptionCloseText: {
        color: 'rgba(255, 255, 255, 0.92)',
        fontSize: 10,
        fontWeight: '700',
        lineHeight: 11,
        textAlign: 'center',
    },
    participantTranscriptionBox: {
        backgroundColor: 'rgba(6, 6, 10, 0.65)',
        paddingHorizontal: 6,
        paddingTop: 3,
        paddingBottom: 3,
        borderRadius: 5,
        width: '100%',
        maxHeight: 50,
    },
    ccToggleBar: {
        position: 'absolute',
        top: -26,
        alignSelf: 'center',
        backgroundColor: 'rgba(15, 15, 20, 0.92)',
        paddingHorizontal: 12,
        paddingVertical: 3,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.22)',
        zIndex: 2,
    },
    ccToggleBarText: {
        color: 'rgba(255, 255, 255, 0.95)',
        fontSize: 11,
        fontWeight: '700',
        letterSpacing: 0.8,
    },
    transcriptionScroll: {
        maxHeight: 45,
    },
    transcriptionScrollContent: {
        flexGrow: 1,
        justifyContent: 'flex-end',
        paddingRight: 2,
    },
    transcriptionLineFinal: {
        textAlign: 'left',
        marginBottom: 2,
        lineHeight: 14,
    },
    transcriptionSpeakerName: {
        color: 'rgba(255, 255, 255, 0.65)',
        fontSize: 9,
        fontWeight: '800',
    },
    transcriptionSpeakerColon: {
        color: 'rgba(255, 255, 255, 0.42)',
        fontSize: 9,
        fontWeight: '600',
    },
    transcriptionUtterance: {
        color: 'rgba(248, 248, 248, 0.96)',
        fontSize: 11,
        fontWeight: '500',
        textShadowColor: 'rgba(0, 0, 0, 0.65)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 1,
    },
    transcriptionLinePartial: {
        textAlign: 'left',
        lineHeight: 14,
        marginTop: 0,
    },
    transcriptionUtterancePartial: {
        color: 'rgba(220, 220, 220, 0.82)',
        fontSize: 11,
        fontWeight: '400',
        fontStyle: 'italic',
    },
});
