const { withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Google Play flags apps whose obfuscation score falls below 25%. R8 is what
 * produces that score, so this plugin ships the keep rules R8 needs to shrink
 * and rename our code without breaking the libraries that resolve classes by
 * name at runtime (JNI, reflection, annotation processors).
 *
 * `minifyEnabled` itself is turned on via
 * `android.enableProguardInReleaseBuilds` in expo-build-properties, since
 * android/ is regenerated by prebuild on every EAS build.
 *
 * Anything removed from here that a library reaches for reflectively fails at
 * runtime in release only -- it never shows up in a debug build.
 */

const PROGUARD_RULES = `
# ---------------------------------------------------------------------------
# Managed by plugins/withProguardRules.js -- edit there, not here.
# ---------------------------------------------------------------------------

# React Native core. The bridge resolves native modules by their Java names and
# JNI looks up members from C++, so neither can be renamed.
-keep,allowobfuscation @interface com.facebook.proguard.annotations.DoNotStrip
-keep,allowobfuscation @interface com.facebook.proguard.annotations.KeepGettersAndSetters
-keep,allowobfuscation @interface com.facebook.common.internal.DoNotStrip

-keep @com.facebook.proguard.annotations.DoNotStrip class *
-keep @com.facebook.common.internal.DoNotStrip class *
-keepclassmembers class * {
    @com.facebook.proguard.annotations.DoNotStrip *;
    @com.facebook.common.internal.DoNotStrip *;
}
-keepclassmembers @com.facebook.proguard.annotations.KeepGettersAndSetters class * {
    void set*(***);
    *** get*();
}

-keep class * extends com.facebook.react.bridge.JavaScriptModule { *; }
-keep class * extends com.facebook.react.bridge.NativeModule { *; }
-keep class * implements com.facebook.react.bridge.NativeModule { *; }
-keepclassmembers class * { @com.facebook.react.uimanager.annotations.ReactProp <methods>; }
-keepclassmembers class * { @com.facebook.react.uimanager.annotations.ReactPropGroup <methods>; }
-keepclassmembers class * { @com.facebook.react.bridge.ReactMethod <methods>; }

# New architecture: TurboModules and Fabric components are looked up by name.
-keep class com.facebook.react.turbomodule.** { *; }
-keep class com.facebook.react.fabric.** { *; }
-keep class com.facebook.jni.** { *; }
-keep class com.facebook.hermes.** { *; }
-dontwarn com.facebook.react.**

# Expo module registry discovers modules reflectively at startup.
-keep class expo.modules.** { *; }
-keep class * extends expo.modules.core.BasePackage { *; }
-keep class * implements expo.modules.core.interfaces.Package { *; }
-keepclassmembers class * { @expo.modules.core.interfaces.ExpoMethod <methods>; }
-dontwarn expo.modules.**

# Reanimated / gesture-handler: worklets are invoked from the UI thread via JNI.
-keep class com.swmansion.reanimated.** { *; }
-keep class com.swmansion.worklets.** { *; }
-keep class com.swmansion.gesturehandler.** { *; }
-keep class com.swmansion.rnscreens.** { *; }
-dontwarn com.swmansion.**

# WebRTC + LiveKit. The native layer calls back into these classes from C++,
# so obfuscating them breaks calls at runtime with no compile-time warning.
-keep class org.webrtc.** { *; }
-keep interface org.webrtc.** { *; }
-keep class io.livekit.** { *; }
-keep class livekit.** { *; }
-keep class com.livekit.** { *; }
-dontwarn org.webrtc.**
-dontwarn io.livekit.**

# CallKeep: bound by the OS through ConnectionService, which resolves the
# service and connection classes from the manifest by name.
-keep class io.wazo.callkeep.** { *; }
-keep class * extends android.telecom.ConnectionService { *; }
-keep class * extends android.telecom.Connection { *; }
-dontwarn io.wazo.callkeep.**

# Firebase / FCM. Messaging services are declared in the manifest and
# instantiated by the framework; models are deserialized reflectively.
-keep class com.google.firebase.** { *; }
-keep class com.google.android.gms.** { *; }
-keep class * extends com.google.firebase.messaging.FirebaseMessagingService { *; }
-keep class io.invertase.firebase.** { *; }
-dontwarn com.google.firebase.**
-dontwarn com.google.android.gms.**

# Google Sign-In
-keep class com.reactnativegooglesignin.** { *; }

# Sentry needs class and line metadata to symbolicate release stack traces.
-keep class io.sentry.** { *; }
-keepattributes SourceFile,LineNumberTable,LocalVariableTable
-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod,Exceptions
-dontwarn io.sentry.**

# Speech recognition binds to the platform SpeechRecognizer service.
-keep class com.wenkesj.voice.** { *; }
-keep class net.no_mad.tts.** { *; }

# expo-sqlite / native SQLite bindings resolved through JNI.
-keep class io.requery.android.database.** { *; }
-keep class org.sqlite.** { *; }

# react-native-svg renders through view managers resolved by name.
-keep public class com.horcrux.svg.** { *; }

# OkHttp / Okio / Retrofit -- used by Firebase, Sentry and LiveKit transitively.
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.**
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**
-keepclassmembers class * { @com.google.gson.annotations.SerializedName <fields>; }

# Kotlin coroutines / metadata used by LiveKit and Firebase SDKs.
-keep class kotlin.Metadata { *; }
-keepclassmembers class kotlinx.coroutines.** { volatile <fields>; }
-dontwarn kotlinx.coroutines.**
-dontwarn kotlin.**

# Enum valueOf() and serialization hooks are reached reflectively.
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}
-keepclassmembers class * implements android.os.Parcelable {
    public static final ** CREATOR;
}

# Keep native method names -- JNI resolves them by exact signature.
-keepclasseswithmembernames class * {
    native <methods>;
}
`;

const MARKER = 'Managed by plugins/withProguardRules.js';

module.exports = function withProguardRules(config) {
  return withDangerousMod(config, [
    'android',
    (config) => {
      const file = path.join(
        config.modRequest.platformProjectRoot,
        'app',
        'proguard-rules.pro'
      );

      const existing = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';

      // Prebuild regenerates this file, but a warm EAS cache can leave ours in
      // place -- appending twice would be harmless yet noisy in the R8 log.
      if (existing.includes(MARKER)) {
        return config;
      }

      fs.writeFileSync(file, `${existing.trimEnd()}\n${PROGUARD_RULES}`, 'utf8');
      return config;
    },
  ]);
};
